name: Build
run-name: Build - ${{ github.ref }}

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  PROJECT_UI_OUTPUT: '/'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and test project
        uses: amilochau/github-actions/build/node@v3
        with:
          relativeOutputPath: ${{ env.PROJECT_UI_OUTPUT }}
