name: Deploy libraries
run-name: Deploy libraries - ${{ github.ref }}

on:
  workflow_dispatch:

concurrency: deploy_libraries

jobs:
  deploy:
    name: Deploy libraries
    runs-on: ubuntu-latest
    environment: PKG
    steps:
      - uses: actions/checkout@v3
      - name: Deploy libraries
        uses: amilochau/github-actions/release/npm@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          npmjsComToken: ${{ secrets.NPMJSCOM_TOKEN }}
